---
- name: set lol_iot_app_roles
  ansible.builtin.set_fact:
    lol_iot_app_roles: []
  when:
    - inventory_hostname == groups['kube_control_plane'][0]

- name: "{{ 'uninstall' if state is defined and state == 'absent' else 'install' }} Apps"
  ansible.builtin.include_role:
    name: "lol_iot/apps/{{ item }}"
  loop: "{{ lol_iot_app_roles | reverse if state is defined and state == 'absent' else lol_iot_app_roles }}"
  when:
    - inventory_hostname == groups['kube_control_plane'][0]
