[tools]
terraform = "1.13.3"
terragrunt = "0.87.5"

[tasks.terragrunt-fmt]
description = "Format all Terragrunt files."
run = "terragrunt hcl fmt"

[tasks.terraform-fmt]
description = "Format all Terraform files."
run = "terraform fmt -recursive"

[tasks.gen-graph]
description = "Generate a graph of the Terragrunt modules."
run = """
for cluster in "home/lol-iot"; do
    terragrunt dag graph --working-dir $cluster/terragrunt \
        | dot -Tsvg -Nshape=rect -Gsplines=ortho -o assets/$cluster/terragrunt/graph.svg;
done
"""

[tasks.encrypt]
description = "Encrypt a secret for Terraform."
run = """
read -sp 'Enter secret to encrypt: ' secret \
&& printf "\\033[36m${secret}\\033[0m\nEncrypted secret: " \
&& printf "${secret}" \
| openssl pkeyutl -encrypt -pubin -inkey public.pem \
| base64 \
| tr -d '\n'\
| xargs -0 printf "\\033[36m%s\\033[0m\n"
"""

[tasks.decrypt]
description = "Decrypt a secret for Terraform."
run = """
read -sp "Enter secret to decrypt: " secret \
&& printf "\\033[36m${secret}\\033[0m\nDecrypted secret: " \
&& printf "${secret}" \
| base64 -d \
| openssl pkeyutl -decrypt -inkey private.pem \
| xargs -0 printf "\\033[36m%s\\033[0m\n"
"""

[tasks.backup]
description = "Backup all Terraform state files."
run = """
tar -czvf `date "+%Y-%m-%d-%H"`_local_secret.tar.gz local_secret
"""
