---
- name: Download files / images
  hosts: k8s_cluster
  roles:
    - { role: kubespray-defaults }
    - { role: lol_iot/download, tags: download, when: "not skip_downloads" }

- name: Install Apps
  hosts: k8s_cluster
  roles:
    - { role: kubespray-defaults }
    - { role: lol_iot/apps, tags: lol_iot_apps }
