---
- name: prepare working directories and variables
  import_tasks: ../../../upstream/roles/download/tasks/prep_download.yml
  when:
    - not skip_downloads | default(false)
  tags:
    - download
    - upload

- name: dwonload files / images
  loop: "{{ lol_iot_downloads | dict2items }}"
  vars:
    download: "{{ download_defaults | combine(item.value) }}"
    include_file: "download_{% if download.container %}container{% else %}file{% endif %}.yml"
  ansible.builtin.include_tasks: ../../../upstream/roles/download/tasks/{{ include_file }}
