# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "../../../../../local_secret/home/lol-iot/terragrunt/storage/local-path-provisioner/terraform.tfstate"
  }
}
