# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~>2"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~>3"
    }
  }
}

provider "kubernetes" {
  config_paths   = ["~/.kube/config", "~/.kube/lol-iot.yaml"]
  config_context = "home/lol-iot/admin"
}

provider "helm" {
  kubernetes = {
    config_paths   = ["~/.kube/config", "~/.kube/lol-iot.yaml"]
    config_context = "home/lol-iot/admin"
  }
}
