name: Terraform and Terragrunt Format Check

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.tf"
      - "**.hcl"

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    name: Check formatting of terraform/terragrunt files
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3.2.0

      - name: Check Terraform format
        run: |
          mise run terraform-fmt
          git diff --exit-code || (echo "::error::terraform-fmt made changes" && exit 1)

      - name: Check Terragrunt HCL format
        run: |
          mise run terragrunt-fmt
          git diff --exit-code || (echo "::error::terragrunt-fmt made changes" && exit 1)
